model_name_or_path: /ds/models/llms/Llama-3.1-8B-Instruct
stage: dpo
pref_loss: wpo
output_dir: cpts_wpo-promptretain0.2-2epoch/llama3.1-8b-instruct/
do_train: true
do_eval: false
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_config.json
# pref_beta: 1.0
simpo_gamma: 1.0
pref_beta: 2.0
margin_beta: 1.0
retain_coef: 0.2
mu_en_path: /netscratch/dshi/projects/MPO/data/mean_harmless/mu_llama31-8b_en.pt
mu_zh_path: /netscratch/dshi/projects/MPO/data/mean_harmless/mu_llama31-8b_zh.pt
mu_ja_path: /netscratch/dshi/projects/MPO/data/mean_harmless/mu_llama31-8b_ja.pt
mu_ko_path: /netscratch/dshi/projects/MPO/data/mean_harmless/mu_llama31-8b_ko.pt
mu_ar_path: /netscratch/dshi/projects/MPO/data/mean_harmless/mu_llama31-8b_ar.pt
mu_bn_path: /netscratch/dshi/projects/MPO/data/mean_harmless/mu_llama31-8b_bn.pt
mu_sw_path: /netscratch/dshi/projects/MPO/data/mean_harmless/mu_llama31-8b_sw.pt
dataset: llama_hpo_data
template: llama3.1
cutoff_len: 1024
max_samples: 100000
overwrite_cache: true
preprocessing_num_workers: 16
logging_steps: 1
save_steps: 500
plot_loss: true
overwrite_output_dir: true
per_device_train_batch_size: 4
gradient_accumulation_steps: 1
learning_rate: 6.0e-07
num_train_epochs: 2
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
save_only_model: true
save_strategy: 'no'
